export const MaxDNSPrefixLen = 253;
export const MaxKeyLen = 63;
export const MaxValueLen = 63;
export const MaxKeyTotalLen = MaxDNSPrefixLen + MaxKeyLen + 1;
export const At = "@";
export const Colon = ":";
export const Dash = "-";
export const Underscore = "_";
export const Dot = ".";
export const ForwardSlash = "/";
export const BackSlash = "\\";
export const BackTick = "`";
export const Bang = "!";
export const Comma = ",";
export const OpenBracket = "[";
export const OpenParens = "(";
export const OpenCurly = "{";
export const CloseBracket = "]";
export const CloseParens = ")";
export const Equal = "=";
export const Space = " ";
export const Tab = "\t";
export const Tilde = "~";
export const CarriageReturn = "\r";
export const NewLine = "\n";

export const OpEquals = "=";
export const OpDoubleEquals = "==";
export const OpNotEquals = "!=";
export const OpIn = "in";
export const OpNotIn = "notin";
