name: "NPM Publish"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - run: npm i
    - run: npm test
    - run: echo "we would publish here"
