name: "Post Merge"

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:

  push:
    name: "Post Merge"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - run: npm i
    - run: make build-docs
    - run: |
      export VERSION=$(node scripts/current_version.js)
      git add ./docs
      git commit -m "Post-merge changes for PR (#${{github.event.number}})
      git tag ${VERSION}
      git push --force-with-lease origin ${VERSION}
      git push --force-with-lease origin HEAD
