name: "Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - run: node scripts/must_increment.js
    - run: npm i
    - run: npm test
    - run: ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
